# Generated by Django 5.0.2 on 2025-04-26 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('churches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('type', models.CharField(choices=[('service', 'Culto'), ('meeting', 'Reunião'), ('class', 'Aula'), ('other', 'Outro')], max_length=20, verbose_name='Tipo')),
                ('date', models.DateTimeField(verbose_name='Data e Hora')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('is_public', models.BooleanField(default=True, verbose_name='Público')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='churches.church', verbose_name='Igreja')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['date'],
            },
        ),
    ]
