# Generated by Django 5.0.2 on 2025-04-26 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('address', models.CharField(max_length=200, verbose_name='Endereço')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('founded_date', models.DateField(verbose_name='Data de Fundação')),
                ('service_times', models.TextField(verbose_name='Horários de Culto')),
                ('is_headquarters', models.BooleanField(default=False, verbose_name='É Sede')),
                ('parent_church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='churches.church')),
            ],
            options={
                'verbose_name': 'Igreja',
                'verbose_name_plural': 'Igrejas',
            },
        ),
        migrations.CreateModel(
            name='ChurchMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('pastor', 'Pastor'), ('leader', 'Líder'), ('member', 'Membro')], max_length=20, verbose_name='Cargo')),
                ('join_date', models.DateField(verbose_name='Data de Ingresso')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='churches.church')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membro da Igreja',
                'verbose_name_plural': 'Membros da Igreja',
            },
        ),
        migrations.AddField(
            model_name='church',
            name='users',
            field=models.ManyToManyField(through='churches.ChurchMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
