# Generated by Django 5.0.2 on 2025-04-26 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='category',
        ),
        migrations.AddField(
            model_name='transaction',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.person', verbose_name='Pessoa'),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('type', models.CharField(choices=[('asset', 'Ativo'), ('liability', 'Passivo'), ('equity', 'Patrimônio'), ('revenue', 'Receita'), ('expense', 'Despesa')], max_length=20, verbose_name='Tipo')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finances.account', verbose_name='Conta Pai')),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='finances.account', verbose_name='Conta'),
        ),
    ]
