name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.14.0-alpha.7]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Create requirements.txt
      run: |
        python -m pip freeze > requirements.txt
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
    - name: Configure Django Project
      run: |
        python manage.py migrate
        python manage.py collectstatic
    - name: Run Tests
      run: |
        python manage.py test
